name: Manual Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LiveKit Source
        uses: actions/checkout@v4
        with:
          repository: 'livekit/client-sdk-android'
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew :sample-app:assembleDebug

      - name: Upload Compiled APK
        uses: actions/upload-artifact@v4
        with:
          name: livekit-sample-debug-apk
          path: sample-app/build/outputs/apk/debug/sample-app-debug.apk
          
